### ISSUE TITLE
Libraries To Be Added

### ISSUE THREAD

**Issue by Rasesh2005** [lepisma/pipwin#46]
pandas-profiling
flask-whooshalchemy

I will Be Updating This Thread If I get Any Such Libraries Not Available through pipwin
I will be thankful if i am able to contribute something to my second most used tool in Command Line after pip

Thank You

**Comment by Rasesh2005** [comment]
wikipedia
speechRecognition
pyperclip
pytorch

If there was a feature to upgrade pipwin like pip that would be able to upgrade it directly using itself

**Comment by samapriya** [comment]
Hi @Rasesh2005 
All the libraries /python packages that can be installed using pipwin comes from https://www.lfd.uci.edu/~gohlke/pythonlibs/. These are pre-compiled wheels and pipwin is helping search for, fetch, and install them. As such those libraries would have to exist as an unofficial package supported at the unofficial python libs website. Also, since you already use pip you should be able to upgrade pipwin easily by using 

```
pip install pipwin --upgrade
```
